config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'user_sessions#login_as', as: :login_as
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'static_pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show edit update destroy] do
    resource :follows, only: [:create, :destroy]
    get 'add_published', on: :collection
    get 'remove_published', on: :collection
  end
  resources :fishes do
    get :complete, on: :collection
    get :complete_edit, on: :collection
    get :ajax_current_weather, on: :collection
    post :ajax_history_weather, on: :collection
    get :list, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  namespace :mypage do
    get 'dashboard'
    get 'follows'
    get 'followers'
    get 'notifications'
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  has_many :fishes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_fishes, through: :likes, source: :fish
  has_many :follows, class_name: "Follow", foreign_key: "follow_id", dependent: :destroy, inverse_of: 'follow'
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy, inverse_of: 'follower'
  has_many :followings, through: :follows, source: :follower
  has_many :followers, through: :reverse_of_follows, source: :follow
  has_many :comments, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  mount_uploader :avatar, AvatarUploader

  before_create -> { self.uuid = 'fippo-' + SecureRandom.hex(10) }

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 8 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :introduction, length: { maximum: 255 }, allow_blank: true
  validates :reset_password_token, uniqueness: true, allow_nil: true

  def own?(object)
    id == object.user_id
  end

  def like(fish)
    like_fishes << fish
  end

  def unlike(fish)
    like_fishes.destroy(fish)
  end

  def like?(fish)
    like_fishes.include?(fish)
  end

  def follow(user_id)
    follows.create(follower_id: user_id)
  end

  def unfollow(user_id)
    follows.find_by(follower_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.ransackable_attributes(auth_object = nil)
    ["access_count_to_reset_password_page", "avatar", "created_at", "crypted_password", "email", "id", "introduction", "is_published", "name", "reset_password_email_sent_at", "reset_password_token", "reset_password_token_expires_at", "salt", "updated_at"]
  end

  def grade_calc
    level1 = 1
    level2 = 3
    level3 = 8
    level4 = 15
    level5 = 30
    num = fishes.count
    case num
    when level1..(level2 - 1)
      1
    when level2..(level3 - 1)
      2
    when level3..(level4 - 1)
      3
    when level4..(level5 - 1)
      4
    else
      5
    end
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[show new create]
  before_action :set_user, only: %i[show edit update destroy]

  def show
    authorize(User)

    @fishes = @user.fishes.includes(:species).order(fishing_date: :desc).page(params[:page])
  end

  def new
    authorize(User)

    @user = User.new
  end

  def edit
    authorize(@user)
  end

  def create
    authorize(User)

    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to fishes_path, notice: t('defaults.message.created', item: User.model_name.human)
    else
      flash.now[:alert] = t('defaults.message.not_created', item: User.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize(@user)

    if @user.update(user_params)
      redirect_to mypage_dashboard_path, notice: t('defaults.message.updated', item: User.model_name.human)
    else
      flash.now[:alert] = t('defaults.message.not_updated', item: User.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    redirect_to login_path, notice: t('defaults.message.deleted', item: User.model_name.human)
  end

  def add_published
    current_user.update!(is_published: true)
    redirect_to request.referer
  end

  def remove_published
    current_user.update!(is_published: false)
    redirect_to request.referer
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :avatar_cache, :introduction, :is_published)
  end
end

app/views/users/_buttons.html.erb
<div class="flex">
  <%= link_to t('defaults.edit'), edit_user_path(current_user), class: "inline-flex items-center rounded-full bg-black px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-slate-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1 mb-1 sm:mb-0", data: {turbo: false} %>
  <%= button_to t('defaults.delete'), user_path(current_user), method: :delete, class: "inline-flex items-center rounded-full bg-white px-3 py-1 text-xs sm:text-sm font-semibold text-black shadow-sm hover:bg-red-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-red-60 mr-1 mb-1 sm:mb-0 border-2 border-red-600", data: {turbo: false}, onclick: 'return confirm("ユーザーを消去しますか？\n投稿を含むすべての情報が削除され復活できなくなります。")' %>
  <%= render 'users/published' %>
</div>

app/views/users/_follow.html.erb
<% if current_user.following?(user)%>
  <%= button_to t('defaults.followed'), user_follows_path(user.id), method: :delete, class: "inline-flex items-center rounded-full bg-indigo-600 px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1 mb-1 sm:mb-0", form: { data: { turbo_confirm: t('defaults.message.unfollow?', item: user.name) } } %>
<% else %>
  <%= button_to t('defaults.follow'), user_follows_path(user.id), method: :post, class: "inline-flex items-center rounded-full border-2 border-indigo-500  bg-white px-3 py-1 text-xs sm:text-sm font-semibold text-black shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1 mb-1 sm:mb-0" %>
<% end %>

app/views/users/_follow_turbo.html.erb
<%= turbo_frame_tag "follow" do %>
  <%= render 'users/follow', { user: user }%>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for user, builder: SimpleForm::Tailwind::FormBuilder, data: { turbo: false } do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <% if current_page?(controller: 'users', action: 'new') %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
  <% end %>
  <%= f.input :avatar, as: :file, onchange: 'previewImage()' %>
  <%= f.hidden_field :avatar_cache %>
  <%= image_tag user.avatar.url, class: 'mb-10 rounded-lg', id: 'preview', size: '100x100' %>
  <%= f.input :introduction, as: :text, input_html: {rows: 5} %>
  <%= f.input :is_published, as: :boolean %>
  <%= f.button :submit %>
<% end %>

<script>
  function previewImage() {
  const target = this.event.target;
  const file = target.files[0];
  const reader  = new FileReader();
  reader.onloadend = function () {
      const preview = document.querySelector("#preview")
      if(preview) {
          preview.src = reader.result;
      }
  }
  if (file) {
      reader.readAsDataURL(file);
  }
  }
</script>

app/views/users/_published.html.erb
<%= turbo_frame_tag "published" do %>
  <% if current_user.is_published %>
    <%= link_to remove_published_users_path, class: "inline-flex items-center rounded-full bg-indigo-600 px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1 mb-1 sm:mb-0", onclick: "return confirm('" + t('.not_published?') + "')" do %>
      <div class="w-4 mr-1"><%= heroicon 'check-circle' %></div>
      <%= t('defaults.published') %>
    <% end %>
  <% else %>
    <%= link_to add_published_users_path, class: "inline-flex items-center rounded-full border-2 border-indigo-600 bg-white px-3 py-1 text-xs sm:text-sm font-semibold text-black shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1 mb-1 sm:mb-0", onclick: "return confirm('" + t('.published?') + "')" do %>
      <div class="w-4 mr-1"><%= heroicon 'key', options: { fill: '#000000' } %></div>
      <%= t('defaults.not_published') %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_status.html.erb
<table class="table-auto text-sm text-slate-500 sm:mx-9 min-w-[100px]">
  <tbody>
    <tr class="h-10">
      <td class="w-24"><%= 'STATUS' %></td>
      <% if user.is_published %>
        <td><%= heroicon 'check-circle', options: { fill: '#000000', class: 'w-4'} %></td>
      <% else %>
        <td><%= heroicon 'key', options: { fill: '#000000', class: 'w-4'} %></td>
      <% end %>
    </tr>
    <tr class="h-8">
      <td><%= t('.post_num') %></td>
      <td><%= user.fishes.count  %></td>
    </tr>
    <tr class="h-8">
      <td><%= t('.follow_num') %></td>
      <td><%= user.followings.count %></td>
    </tr>
    <tr class="h-8">
      <td><%= t('.follower_num') %></td>
      <td><%= user.followers.count %></td>
    </tr>
    <tr class="h-8">
      <td><%= t('.grade') %></td>
      <td><%= user.grade %></td>
      <%= image_tag 'fish' + user.grade.to_s + '.png', size: '30x30', class: 'absolute bottom-6 sm:right-4 sm:block hidden'%>
      <%= image_tag 'fish' + user.grade.to_s + '.png', size: '30x30', class: 'absolute bottom-6 sm:hidden left-36 '%>
    </tr>
  </tbody>
</table>

app/views/users/_user.html.erb
<div class="bg-form p-6 rounded-2xl relative">
  <div class="flex flex-col">
    <div class="flex justify-between mr-2">
      <%= render 'users/user_info', { user: user } %>
      <% if logged_in? %>
        <%= render 'users/follow', {user: user} %>
      <% end %>
    </div>
    <div class="flex-grow h-[75px] break-all pr-6 pb-6 overflow-y-scroll"><%= simple_format(user.introduction)%></div>
  </div>
</div>

app/views/users/_user_info.html.erb
<div class="flex items-start mb-4">
  <%= link_to user, class: "flex max-w-xs items-center rounded-ful text-sm focus:outline-none shrink-0", data: { turbo: false } do %>
  <%= image_tag user.avatar_url(:thumbnail), class: "rounded-full h-8 w-8 sm:h-12 sm:w-12", alt: User.human_attribute_name(:avatar) %>
  <% end %>
  <div class="flex-grow px-5 text-base whitespace-nowrap overflow-x-scroll">
    <%= user.name %>
  </div>
</div>

app/views/users/_user_info_lg.html.erb
<div class="flex items-start mb-4">
  <%= link_to user, class: "flex max-w-xs items-center rounded-ful text-sm focus:outline-none shrink-0", data: { turbo: false } do %>
  <%= image_tag user.avatar_url(:thumbnail), class: "rounded-full h-12 w-12 sm:h-16 sm:w-16", alt: User.human_attribute_name(:avatar) %>
  <% end %>
  <div class="px-5 text-base sm:text-xl break-all">
    <%= user.name %>
  </div>
</div>

app/views/users/_users.html.erb
<div class="max-w-[800px] m-auto mb-16">
  <%= turbo_frame_tag "users-list" do %>
    <div class="grid sm:grid-cols-2 grid-cols-1 gap-4">
      <%= render users %>
    </div>
    <%= paginate @users, class: 'mt-3'%>
  <% end %>
</div>

app/views/users/edit.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form py-16 px-6 sm:py-24 lg:px-8 max-w-[800px] m-auto my-16 rounded-2xl">
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t('.title') %></h2>
  </div>
  <div class="mx-auto mt-6 max-w-xl sm:mt-12">
    <%= render 'form', { user: @user } %>
  </div>
</div>

app/views/users/new.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form py-16 px-6 sm:py-24 lg:px-8 max-w-[800px] m-auto my-16 rounded-2xl">
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t('.title') %></h2>
  </div>
  <div class="mx-auto mt-6 max-w-xl sm:mt-12">
    <%= render 'form', { user: @user } %>
  </div>
</div>

app/views/users/show.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form p-6 max-w-[800px] m-auto my-16 rounded-2xl relative">
  <div class="mx-auto">
    <div class="sm:flex">
      <div class="flex-grow flex flex-col sm:border-r-[1px] sm:border-spacing-100">
        <div class="flex justify-between mr-2">
          <%= render 'user_info_lg', { user: @user } %>
          <% if logged_in? %>
            <% if current_user.id != @user.id %>
              <%= render 'users/follow_turbo', {user: @user} %>
            <% end %>
          <% end %>
        </div>
        <div class="flex-grow min-h-[50px] break-all pr-6 pb-6"><%= simple_format(@user.introduction)%></div>
      </div>
      <hr class="my-3">
      <%= render 'status', {user: @user } %>
    </div>
  </div>
</div>

<% if @user.is_published%>
  <%= render 'fishes/fishes', { fishes: @fishes }%>
<% else %>
<div class="flex justify-center">
  <div class="rounded-full bg-black px-3 py-1 text-xs sm:text-sm font-semibold text-white"><%= t('.not_published') %></div>
</div>
<% end %>