config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'user_sessions#login_as', as: :login_as
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'static_pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show edit update destroy] do
    resource :follows, only: [:create, :destroy]
    get 'add_published', on: :collection
    get 'remove_published', on: :collection
  end
  resources :fishes do
    get :complete, on: :collection
    get :complete_edit, on: :collection
    get :ajax_current_weather, on: :collection
    post :ajax_history_weather, on: :collection
    get :list, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  namespace :mypage do
    get 'dashboard'
    get 'follows'
    get 'followers'
    get 'notifications'
  end
end

app/views/shared/_flash.html.erb
<div class="absolute top-[60px] left-1/2 -translate-x-1/2 w-full max-w-[800px] z-50">
<% if flash[:notice] %>
  <div class="relative max-w-[800px] mx-auto p-4 mt-3 mb-4 text-sm text-blue-700 bg-blue-100 rounded-lg  dark:text-blue-800 flex justify-between" role="alert">
    <%= flash[:notice] %>
    <%= heroicon "x-circle", options: { class: "js-flash-close w-5" } %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="relative max-w-[800px] mx-auto p-4 mt-3 mb-4 text-sm text-red-700 bg-red-100 rounded-lg dark:text-red-800 flex justify-between" role="alert">
    <%= flash[:alert] %>
    <%= heroicon "x-circle", options: { class: "js-flash-close w-5" } %>
  </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<div class="min-h-full">
  <nav class="bg-[#EAEAEA]">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-end">
        <nav class="sm:ml-10 flex items-center sm:space-x-3">
          <%= link_to t('defaults.terms_of_service'), "https://erratic-monday-e75.notion.site/67b90b44176f44738fe77540c19898b8", class: "text-black hover:bg-gray-100 rounded-md px-1 py-2 text-xs sm:text-sm font-medium", target: "_blank"%>
          <%= link_to t('defaults.privacy_policy'), "https://kiyac.app/privacypolicy/LRCKwHte0QknxcZperWC", class: "text-black hover:bg-gray-100 rounded-md px-1 py-2 text-xs sm:text-sm font-medium", target: "_blank"%>
          <%= link_to t('defaults.inquire'), 'https://forms.gle/2eff66iGxxDysLXz5', class: "text-black hover:bg-gray-100 rounded-md px-1 py-2 text-xs sm:text-sm font-medium", target: "_blank"%>
          <%= link_to 'https://twitter.com/takuma1996300', class: "text-black hover:bg-gray-100 rounded-md px-1 py-2 text-xs sm:text-sm font-medium", target: "_blank" do %>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="currentColor"
              viewBox="0 0 24 24">
              <path
                d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z" />
            </svg>
          <% end %>
          <p class="text-black rounded-md px-1 py-2 text-xs sm:text-sm font-medium"><%= t('defaults.copywriting') %></p>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_header.html.erb
<div class="min-h-full">
  <nav class="bg-[#4BA9FF]">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 items-center justify-between">
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <%= link_to root_path, data: {turbo: false} do %>
              <%= image_tag "fippo.png", class: "sm:h-10 sm:w-40 w-28",alt: t('defaults.fippo_map') %>
            <% end %>
          </div>
        </div>
        <nav class="bolck">
          <div class="ml-4 flex items-center md:ml-6">
            <%= link_to t('defaults.map'), fishes_path, class: "text-white hover:bg-gray-100 hover:text-black rounded-md px-1 py-2 mr-1 m:mr-2 text-xs sm:text-sm font-medium", 'data-turbo': false %>
            <%= link_to t('defaults.list'), list_fishes_path, class: "text-white hover:bg-gray-100 hover:text-black rounded-md px-1 py-2 mr-1 sm:mr-2 text-xs sm:text-sm font-medium", 'data-turbo': false %>
            <% if logged_in? %>
              <%# ベルマーク %>
              <%= link_to mypage_notifications_path, class: "relative rounded-full bg-[#4BA9FF] p-1 text-white hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800 mr-1 sm:mr-3" do %>
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
                </svg>
                <% if unchecked_notifications.any? %>
                  <div class="absolute top-0 right-0"><%= heroicon 'information-circle', options: { class: "w-4", fill: "#ff3399" } %></div>
                <% end %>
              <% end %>
              <!-- Profile dropdown -->
              <div class="relative">
                <div>
                  <button type="button" class="flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="js-user-menu-button" aria-expanded="false" aria-haspopup="true">
                    <%= image_tag current_user.avatar_url(:thumbnail), class: "h-8 w-8 rounded-full", alt: User.human_attribute_name(:avatar) %>
                  </button>
                  <div class="hidden absolute right-0 z-10 mt-2 w-32 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                    <%= link_to t('defaults.my_page'), mypage_dashboard_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", tabindex: "-1", id: "user-menu-item-0", data: {turbo: false} %>
                    <%= button_to t('defaults.logout'), logout_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", tabindex: "-1", id: "user-menu-item-2", data: {turbo: false} %>
                  </div>
                </div>
              </div>
            <% else %>
              <%= link_to t('defaults.login'), login_path, class: "text-white hover:bg-gray-500 rounded-md px-1 py-2 text-xs sm:text-sm font-medium"%>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_loading.html.erb
<div class="loader-wrap">
  <div class="loader"></div>
</div>

app/views/shared/_to_map.html.erb
<%= link_to t('fishes.complete.to_map'), fishes_path, class: "inline-flex items-center rounded-full bg-black px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-slate-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60", data: {turbo: false} %>