config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'user_sessions#login_as', as: :login_as
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'static_pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show edit update destroy] do
    resource :follows, only: [:create, :destroy]
    get 'add_published', on: :collection
    get 'remove_published', on: :collection
  end
  resources :fishes do
    get :complete, on: :collection
    get :complete_edit, on: :collection
    get :ajax_current_weather, on: :collection
    post :ajax_history_weather, on: :collection
    get :list, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  namespace :mypage do
    get 'dashboard'
    get 'follows'
    get 'followers'
    get 'notifications'
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def dashboard
    @fishes = current_user.fishes.includes(:species).page(params[:page])
  end

  def follows
    @users = current_user.followings.order(follows: :desc).page(params[:page])
  end

  def followers
    @users = current_user.followers.order(follows: :desc).page(params[:page])
  end

  def notifications
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
    @notifications = @notifications.where.not(visitor_id: current_user.id)
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
  def current_mypage(action)
    current_page?(controller: 'mypage', action:) ? 'bg-indigo-200 hover:bg-indigo-300 border-indigo-800 text-indigo-500 text-sm border-b-2 py-4 px-2' : 'hover:bg-indigo-100 text-sm text-slate-500 py-4 px-3'
  end
end

app/views/mypage/_nav.html.erb
<div class="max-w-[800px] m-auto my-8 rounded-2xl">
  <nav class="flex">
    <%= link_to t('mypage.dashboard.title'), mypage_dashboard_path, class: current_mypage('dashboard') %>
    <%= link_to t('mypage.follows.title'), mypage_follows_path, class: current_mypage('follows') %>
    <%= link_to t('mypage.followers.title'), mypage_followers_path, class: current_mypage('followers') %>
    <%= link_to t('mypage.notifications.title'), mypage_notifications_path, class: current_mypage('notifications') %>
  </nav>
</div>

app/views/mypage/_profile.html.erb
<div class="bg-form py-6 px-6 max-w-[800px] m-auto mb-16 rounded-2xl relative">
  <div class="mx-auto">
    <div class="sm:flex">
      <div class="flex-grow flex flex-col sm:border-r-[1px] sm:border-spacing-100">
        <%= render 'users/user_info_lg', { user: current_user } %>
        <div class="flex-grow min-h-[50px] break-all pr-6 pb-6 "><%= simple_format(current_user.introduction)%></div>
        <%= render 'users/buttons'%>
      </div>
      <hr class="my-3">
      <%= render 'users/status', { user: current_user} %>
    </div>
  </div>
</div>

app/views/mypage/dashboard.html.erb
<% set_meta_tags title: t('.title') %>

<%= render 'nav' %>

<%= render 'profile' %>

<%= render 'fishes/fishes', { fishes: @fishes }%>

app/views/mypage/followers.html.erb
<% set_meta_tags title: t('.title') %>

<%= render 'nav' %>

<%= render 'users/users', { users: @users }%>

app/views/mypage/follows.html.erb
<% set_meta_tags title: t('.title') %>

<%= render 'nav' %>

<%= render 'users/users', { users: @users }%>

app/views/mypage/notifications.html.erb
<% set_meta_tags title: t('.title') %>

<%= render 'nav' %>

<div class="max-w-[800px] m-auto my-16">
  <div class="grid sm:grid-cols-2 grid-cols-1 gap-4">
    <div class="bg-form rounded-2xl h-[300px] overflow-y-scroll mb-4">
      <h2 class="text-lg my-4 p-2 text-center">FippoMapからお知らせ</h2>
      <div class="min-h-10 border-t-[1px] border-t-black/5 text-sm p-2 ">
        <p class="text-xs text-slate-500">2023年04月09日</p>
        <p class="">Googleでログインできるようになりました！！</p>
        <p class="text-right text-slate-500 text-xs mt-1"><%= time_ago_in_words('2023-04-09').upcase %></p>
      </div>
      <div class="min-h-10 border-t-[1px] border-t-black/5 text-sm p-2 ">
        <p class="text-xs text-slate-500">2023年04月08日</p>
        <p class="">あなたをフォロー、あなたの投稿にいいね・コメントをした時に通知が来るようになりました！！</p>
        <p class="text-right text-slate-500 text-xs mt-1"><%= time_ago_in_words('2023-04-08').upcase %></p>
      </div>
      <div class="min-h-10 border-t-[1px] border-t-black/5 text-sm p-2 ">
        <p class="text-xs text-slate-500">2023年04月06日</p>
        <p class="">マイページでフォロー・フォロワーが見れるようになりました！！</p>
        <p class="text-right text-slate-500 text-xs mt-1"><%= time_ago_in_words('2023-04-06').upcase %></p>
      </div>
      <div class="min-h-10 border-t-[1px] border-t-black/5 text-sm p-2 ">
        <p class="text-xs text-slate-500">2023年04月05日</p>
        <p class="">投稿にコメントができるようになりました！！</p>
        <p class="text-right text-slate-500 text-xs mt-1"><%= time_ago_in_words('2023-04-05').upcase %></p>
      </div>
      <div class="min-h-10 border-t-[1px] border-t-black/5 text-sm p-2 ">
        <p class="text-xs text-slate-500">2023年04月04日</p>
        <p class="">FippoMapをMVPリリースしました！！</p>
        <p class="text-right text-slate-500 text-xs mt-1"><%= time_ago_in_words('2023-04-04').upcase %></p>
      </div>
    </div>
    <%= render 'notifications/notifications', {notifications: @notifications} %>
  </div>
</div>