config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    get '/login_as/:user_id', to: 'user_sessions#login_as', as: :login_as
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'static_pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  post "oauth/callback", to: "oauths#callback"
  get "oauth/callback", to: "oauths#callback"
  get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  delete 'logout', to: 'user_sessions#destroy'
  resources :password_resets, only: %i[new create edit update]
  resources :users, only: %i[new create show edit update destroy] do
    resource :follows, only: [:create, :destroy]
    get 'add_published', on: :collection
    get 'remove_published', on: :collection
  end
  resources :fishes do
    get :complete, on: :collection
    get :complete_edit, on: :collection
    get :ajax_current_weather, on: :collection
    post :ajax_history_weather, on: :collection
    get :list, on: :collection
    resources :comments, only: %i[create edit update destroy], shallow: true
  end
  resources :likes, only: %i[create destroy]
  namespace :mypage do
    get 'dashboard'
    get 'follows'
    get 'followers'
    get 'notifications'
  end
end

app/models/fish.rb
class Fish < ApplicationRecord
  default_scope -> { order(fishing_date: :desc) }
  belongs_to :user
  belongs_to :species
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  mount_uploader :image, FishImageUploader

  enum weather: { fine: 0, sunny: 1, cloudy: 2, fog: 3, drizzle: 4, rain: 5, snow: 6, thunderstorm: 7 }
  enum wind_direction: { north: 0, north_northeast: 1, northeast: 2, east_northeast: 3, east: 4, east_southeast: 5, southeast: 6, south_southeast: 7, south: 8, south_southwest: 9, southwest: 10, west_southwest: 11, west: 12, west_northwest: 13, northwest: 14, north_northwest: 15 }
  enum tide_name: { spring: 0, middle: 1, neap: 2, long: 3, wakashio: 4 }

  validates :fishing_date, presence: true,
            date: {
              # 1900年1月1日より後で現在の日付までの範囲のみ許可する
              after: Date.new(1900, 1, 1),
              before: ->(obj) { Time.zone.now }
            }
  validates :body, presence: true, length: { maximum: 255 }
  validates :latitude, presence: true, numericality: { in: -90..90, message: 'は-90~90で入力してください' }
  validates :longitude, presence: true, numericality: { in: -180..180, message: 'は-180~180で入力してください' }
  validates :size, numericality: { only_integer: true }, allow_blank: true
  validates :weather, presence: true
  validates :wind_direction, presence: true
  validates :wind_speed, presence: true, numericality: true
  validates :temperature, presence: true, numericality: true
  validates :tide_name, presence: true

  scope :published, -> { where(user: { is_published: true }) }

  def latest?
    Date.parse(fishing_date.to_s) == Time.zone.today
  end

  def species_default
    species_id ? species.name : ''
  end

  def self.ransackable_associations(auth_object = nil)
    ["likes", "species", "user", "users"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["body", "created_at", "fishing_date", "id", "user_id", "image", "latitude", "longitude", "size", "species_id", "temperature", "tide_name", "updated_at", "user_id", "weather", "wind_direction", "wind_speed"]
  end

  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and fish_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        fish_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(fish_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      fish_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController
  include FishHelper
  skip_before_action :verify_authenticity_token
  skip_before_action :require_login, only: %i[index list show]
  before_action :set_fish, only: %i[show edit update destroy]

  def index
    authorize(Fish)

    @q = Fish.ransack(params[:q])
    @fishes = @q.result(distinct: true).includes(:species, :user)
    if logged_in?
      @fishes = @fishes.published.or(@fishes.where(user_id: current_user.id))
    else
      @fishes = @fishes.published
    end
  end

  def list
    authorize(Fish)

    @fishes = Fish.includes(:species, :user).page(params[:page]).per(20)
    if logged_in?
      @fishes = @fishes.published.or(@fishes.where(user_id: current_user.id))
    else
      @fishes = @fishes.published
    end
  end

  def show
    authorize(@fish)

    @user = @fish.user
    @comment = Comment.new
    @comments = @fish.comments.includes(:user).order(created_at: :asc)
  end

  def new
    authorize(Fish)

    session[:latitude] = params[:latitude]
    session[:longitude] = params[:longitude]
    @fish = Fish.new
  end

  def edit
    authorize(@fish)
  end

  def create
    authorize(Fish)

    Fish.transaction do
      species = create_or_find_species
      @fish = current_user.fishes.new(fish_params)
      @fish.species_id = species.id
      @fish.save!
      current_user.update!(grade: current_user.grade_calc)
      session[:latitude] = params[:fish][:latitude]
      session[:longitude] = params[:fish][:longitude]
      session[:fish_id] = @fish.id
      redirect_to complete_fishes_path, notice: t('defaults.message.created', item: Fish.model_name.human)
    rescue ActiveRecord::RecordInvalid => exception
      flash.now[:alert] = t('defaults.message.not_created', item: Fish.model_name.human)
      render action: :new, status: :unprocessable_entity
    end
  end

  def update
    authorize(@fish)

    Fish.transaction do
      species = create_or_find_species
      @fish.assign_attributes(fish_params)
      @fish.species_id = species.id
      @fish.save!
      session[:latitude] = params[:fish][:latitude]
      session[:longitude] = params[:fish][:longitude]
      session[:fish_id] = @fish.id
      redirect_to complete_edit_fishes_path, notice: t('defaults.message.updated', item: Fish.model_name.human)
    rescue ActiveRecord::RecordInvalid => exception
      flash.now[:alert] = t('defaults.message.not_updated', item: Fish.model_name.human)
      render action: :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize(@fish)

    Fish.transaction do
      @fish.destroy!
      current_user.update!(grade: current_user.grade_calc)
      redirect_to fishes_path, notice: t('defaults.message.deleted', item: Fish.model_name.human)
    end
  end

  def complete
    fish_id = session[:fish_id]
    @fish = Fish.find(fish_id)
  end

  def complete_edit
    fish_id = session[:fish_id]
    @fish = Fish.find(fish_id)
  end

  # ajaxで現在の気象情報を取得するためのメソッド
  def ajax_current_weather
    date = Time.current
    latitude = session[:latitude]
    longitude = session[:longitude]
    response = weather_current_request(latitude, longitude)
    respond_to do |format|
      format.json { render json: input_current_default(date, latitude, longitude, response) }
    end
  end

  def ajax_history_weather
    date = params[:date]
    latitude = params[:latitude]
    longitude = params[:longitude]
    response = weather_history_request(date, latitude, longitude)
    respond_to do |format|
      format.json { render json: input_history_default(date.to_time, latitude, longitude, response) }
    end
  end

  private

  def create_or_find_species
    if Species.exists?(name: species_params[:species])
      Species.find_by(name: species_params[:species])
    else
      Species.create!(name: species_params[:species])
    end
  end

  def fish_params
    params.require(:fish).permit(:image, :image_cache, :fishing_date, :body, :species_id, :size, :latitude, :longitude, :weather, :wind_direction, :wind_speed, :temperature, :tide_name)
  end

  def species_params
    params.require(:fish).permit(:species)
  end

  def set_fish
    @fish = Fish.find(params[:id])
    session[:latitude] = @fish.latitude
    session[:longitude] = @fish.longitude
  end
end

app/helpers/fish_helper.rb
module FishHelper
  def calculation_tide(date)
    y = date.year
    m = date.month
    d = date.day
    c = 0
    case m
    when 2, 4, 5
      c = 2
    when 6
      c = 4
    when 7
      c = 5
    when 8
      c = 6
    when 9
      c = 7
    when 10
      c = 8
    when 11
      c = 9
    when 12
      c = 10
    end
    age = (((y - 11) % 19) * 11 + c + d) % 30   # 月齢
    case age
    when 1, 2, 14, 15, 16, 17, 29, 30
      "spring"
    when 3, 4, 5, 6, 12, 13, 18, 19, 20, 21, 27, 28
      "middle"
    when 7, 8, 9, 22, 23, 24
      "neap"
    when 10, 25
      "long"
    when 11, 26
      "wakashio"
    end
  end

  def calculation_weather(id)
    case id
    when 200, 201, 202, 210, 211, 212, 221, 230, 231, 232
      'thunderstorm'
    when 300, 301, 302, 310, 311, 312, 313, 314, 321
      'drizzle'
    when 500, 501, 502, 503, 504, 511, 520, 521, 522, 531
      'rain'
    when 600, 601, 602, 611, 612, 613, 615, 616, 620, 621, 622
      'snow'
    when 701, 711, 721, 731, 741, 751, 761, 762, 771, 781
      'fog'
    when 800
      'fine'
    when 801
      'sunny'
    when 802, 803, 804
      'cloudy'
    end
  end

  def calculation_wind_direction(deg)
    case deg
    when 0..11.25, 348.75..360
      'north'
    when 11.25..33.75
      'north_northeast'
    when 33.75..56.25
      'northeast'
    when 56.25..78.75
      'east_northeast'
    when 78.75..101.25
      'east'
    when 101.25..123.75
      'east_southeast'
    when 123.75..146.25
      'southeast'
    when 146.25..168.75
      'south_southeast'
    when 168.75..191.25
      'south'
    when 191.25..213.75
      'south_southwest'
    when 213.75..236.25
      'southwest'
    when 236.25..258.75
      'west_southwest'
    when 258.75..281.25
      'west'
    when 281.25..303.75
      'west_northwest'
    when 303.75..326.25
      'northwest'
    when 326.25..348.75
      'north_northwest'
    end
  end

  def weather_current_request(latitude, longitude)
    client    = HTTPClient.new
    url       = "https://api.openweathermap.org/data/2.5/weather?lat=" + latitude + "&lon=" + longitude + "&appid=" + ENV.fetch('OPEN_WEATHER_API_KEY') + "&lang=ja&units=metric"
    response  = client.get(url)
    JSON.parse(response.body)
  end

  def weather_history_request(date, latitude, longitude)
    date_unix = Time.parse(date).to_i.to_s
    client    = HTTPClient.new
    url       = "https://api.openweathermap.org/data/3.0/onecall/timemachine?lat=" + latitude + "&lon=" + longitude + "&dt=" + date_unix + "&appid=" + ENV.fetch('OPEN_WEATHER_API_KEY') + "&lang=ja&units=metric"
    response  = client.get(url)
    JSON.parse(response.body)
  end

  def input_current_default(date, latitude, longitude, response)
    weather = calculation_weather(response['weather'][0]['id'])
    wind_direction = calculation_wind_direction(response['wind']['deg'])
    wind_speed = response['wind']['speed']
    temperature = response['main']['temp']
    tide_name = calculation_tide(date)
    default = { fishing_date: date.strftime("%Y-%m-%d %H:%M:%S"),
                latitude:,
                longitude:,
                weather:,
                wind_direction:,
                wind_speed:,
                temperature:,
                tide_name: }
  end

  def input_history_default(date, latitude, longitude, response)
    weather = calculation_weather(response['data'][0]['weather'][0]['id'])
    wind_direction = calculation_wind_direction(response['data'][0]['wind_deg'])
    wind_speed = response['data'][0]['wind_speed']
    temperature = response['data'][0]['temp']
    tide_name = calculation_tide(date)
    default = { fishing_date: date.strftime("%Y-%m-%d %H:%M:%S"),
                latitude:,
                longitude:,
                weather:,
                wind_direction:,
                wind_speed:,
                temperature:,
                tide_name: }
  end
end

app/views/fishes/_complete.html.erb
<div class="mx-auto mt-6 max-w-xl sm:mt-12">
  <%= image_tag 'fish' + current_user.grade.to_s + '.png', size: '50x50', class: 'm-auto'%>
  <p class='text-center mb-10'><%= t('.grade') + current_user.grade.to_s %></p>
  <div class="flex justify-center">
    <%= link_to t('.to_twitter'), "https://twitter.com/share?ref_src=twsrc%5Etfw", class: 'twitter-share-button flex', data: {
                  lang: "ja",
                  'show-count': false,
                  size: "large",
                  text: t('.text'),
                  hashtags: t('.hashtags'),
                  url: ENV.fetch('ORIGIN') + '/fishes/' + @fish.id.to_s
                  }
    %>
  </div>
  <div class="flex gap-2">
    <%= link_to t('.to_map'), fishes_path, class: 'block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mt-5', 'data-turbo': false %>
    <%= link_to t('.to_fish_details'), @fish, class: 'block w-full rounded-md bg-indigo-600 px-3.5 py-2.5 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mt-5', 'data-turbo': false %>
  </div>
</div>

<script src="https://platform.twitter.com/widgets.js" charset="utf-8" defer></script>

app/views/fishes/_current_position.html.erb
<button class="bg-white w-10 h-10 m-[10px] rounded-sm" onClick="changeCenter()">
  <div class="w-7 h-7 m-auto">
    <%= heroicon "map-pin" %>
  </div>
</button>

app/views/fishes/_fish.html.erb
<div class="bg-form p-6 rounded-2xl relative">
  <div class="flex flex-col">
    <%= render 'fishes/fish_info', { fish: fish } %>
    <div class="flex-grow h-[75px] break-all pr-6 pb-6 overflow-y-scroll"><%= simple_format(fish.body)%></div>
  </div>
</div>

app/views/fishes/_fish_info.html.erb
<div class="flex items-start mb-4">
  <%= link_to fish, class: "flex max-w-xs items-center rounded-ful text-sm focus:outline-none shrink-0", data: { turbo: false } do %>
    <%= image_tag fish.image_url(:thumbnail), class: "rounded-full h-8 w-8 sm:h-12 sm:w-12", alt: Fish.human_attribute_name(:image) %>
  <% end %>
  <div class="flex-grow px-5 text-base whitespace-nowrap overflow-x-scroll">
    <p class="text-xs text-slate-500"><%= fish.fishing_date.strftime("%Y年%m月%d日") %></p>
    <%= fish.species.name %>
  </div>
  <% if logged_in? %>
    <%= render 'fishes/like', { fish: fish } %>
  <% end %>
</div>

app/views/fishes/_fishes.html.erb
<div class="max-w-[800px] m-auto mb-16">
  <%= turbo_frame_tag "fishes-list" do %>
    <div class="grid sm:grid-cols-2 grid-cols-1 gap-4">
      <%= render fishes %>
    </div>
    <%= paginate @fishes, class: 'mt-3'%>
  <% end %>
</div>

app/views/fishes/_like.html.erb
<%= turbo_frame_tag "like" do %>
  <div class="flex">
    <% if current_user.like?(fish) %>
      <%= button_to like_path(current_user.likes.find_by(fish_id: fish.id)), method: :delete do %>
        <%= heroicon 'heart', options: { class: "w-4 mr-1", fill: "#ff3399" } %>
      <% end %>
    <% else %>
      <%= button_to likes_path(fish_id: fish.id), method: :post do %>
        <%= heroicon 'heart', options: { class: "w-4 mr-1 bg-primary-500", fill: '#ffffff', stroke: '#ff3399', 'stroke-width': '2' } %>
      <% end %>
    <% end %>
    <p class="text-[13px]"><%= fish.likes.count %></p>
  </div>
<% end %>

app/views/fishes/_map_fish.html.erb
markerLatLng = new google.maps.LatLng({lat: <%= fish.latitude.to_s %>, lng: <%= fish.longitude.to_s %> });
marker[<%= fish.id %>] = new markerWithLabel.MarkerWithLabel({
  position: markerLatLng,
  map: map,
  icon: {
    url: "<%= fish.latest? ? image_url('fish_new' + fish.user.grade.to_s + '.png') : image_url('fish' + fish.user.grade.to_s + '.png') %>",
    scaledSize: new google.maps.Size(30, 30)
  },
  labelContent: '<%= fish.species.name %>',
  labelClass: "marker-labels",
});
// 吹き出しの追加
infoWindow[<%= fish.id %>] = new google.maps.InfoWindow({
  position: markerLatLng,
  content: `
          <table class="table-auto mt-3">
          <tbody>
            <tr>
              <td class="w-14"><%= User.human_attribute_name(:name) %></td>
              <td><%= fish.user.name %></td>
            </tr>
            <tr>
              <td class="w-14"><%= Fish.human_attribute_name(:fishing_date) %></td>
              <td><%= fish.fishing_date.strftime("%Y年%m月%d日") %></td>
            </tr>
            <tr>
              <td><%= Fish.human_attribute_name(:size) %></td>
              <td><%= fish.size %></td>
            </tr>
            <tr>
              <td><%= Fish.human_attribute_name(:weather) %></td>
              <td><%= fish.weather_i18n %>　<%= fish.temperature%>℃</td>
            </tr>
            <tr>
              <td><%= t('defaults.wind') %></td>
              <td><%= fish.wind_direction_i18n %>　<%= fish.wind_speed %>m/s</td>
            </tr>
            <tr>
              <td><%= Fish.human_attribute_name(:tide_name) %></td>
              <td><%= fish.tide_name_i18n %></td>
            </tr>
          </tbody>
        </table>
  `,
  pixelOffset: new google.maps.Size(0, -50)
});

markerEvent(<%= fish.id %>); // マーカーにクリックイベントを追加

// マーカーをホバーした時に吹き出しを表示
function markerEvent(i) {
  marker[i].addListener('click', function() { // マーカーをクリックしたとき
    location.href = "/fishes/" + i
  });
  marker[i].addListener('mouseover', function() { // マーカーをクリックしたとき
    infoWindow[i].open(map, marker[i]); // 吹き出しの表示
  });
  marker[i].addListener('mouseout', function(){
    infoWindow[i].close(map, marker[i]);
  });
}

app/views/fishes/_post_buttons.html.erb
<div class="flex">
  <button type="button" class="js-add-post inline-flex items-center rounded-full bg-indigo-600 px-3 py-1
  text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1 whitespace-nowrap ">
    投稿する
  </button>
  <button type="button" class="js-to-form-post inline-flex items-center rounded-full bg-indigo-600 px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mr-1 whitespace-nowrap  hidden" onclick="toFormPost()">
    この位置に投稿する
  </button>
  <button type="button" class="js-cancel-post inline-flex items-center rounded-full bg-indigo-600 px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600 mr-1 whitespace-nowrap hidden">
    キャンセル
  </button>
</div>

app/views/fishes/complete.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form py-16 px-6 sm:py-24 lg:px-8 max-w-[800px] m-auto my-16 rounded-2xl">
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t('.title') %></h2>
  </div>
  <%= render 'complete', { fish: @fish } %>
</div>

app/views/fishes/complete_edit.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form py-16 px-6 sm:py-24 lg:px-8 max-w-[800px] m-auto my-16 rounded-2xl">
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t('.title') %></h2>
  </div>
  <%= render 'complete', { fish: @fish } %>
</div>

app/views/fishes/new.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form py-16 px-6 sm:py-24 lg:px-8 max-w-[800px] m-auto my-16 rounded-2xl">
  <div class="mx-auto max-w-2xl text-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= t('.title') %></h2>
  </div>
  <div class="mx-auto mt-6 max-w-xl sm:mt-12">
    <%= render 'form', { fish: @fish } %>
    <div id ='default_flag' class='hidden' >default</div>
  </div>
</div>

app/views/fishes/show.html.erb
<% set_meta_tags title: t('.title') %>

<div class="bg-form py-16 px-6 sm:py-24 lg:px-8 max-w-[800px] m-auto my-16 rounded-2xl relative">
  <div class='absolute top-3 left-3 '>
    <%= render 'shared/to_map' %>
  </div>
  <div class="mx-auto max-w-xl">
    <div class="flex">
      <div class="flex-grow">
        <%= render 'users/user_info_lg', { user: @fish.user } %>
      </div>
      <% if logged_in? %>
        <div class="flex flex-col justify-between shrink-0">
          <% if current_user.own?(@fish) %>
            <div class="flex">
                <%= link_to t('defaults.edit'), edit_fish_path(@fish), class: "inline-flex items-center rounded-full bg-black px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-slate-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1", data: {turbo: false} %>
                <%= button_to t('defaults.delete'), fish_path(@fish), method: :delete, class: "inline-flex items-center rounded-full bg-black px-3 py-1 text-xs sm:text-sm font-semibold text-white shadow-sm hover:bg-slate-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-60 mr-1", onclick: "return confirm('" + t('defaults.message.delete_confirm') + "')", data: {turbo: false} %>
            </div>
          <% else %>
            <%= render 'users/follow_turbo', {user: @user} %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="flex justify-center">
      <div>
        <%= image_tag @fish.image.url, class: 'rounded-lg mt-10', id: 'preview', size: '200x200' %>
        <div class="flex justify-between items-start mb-10">
          <% if logged_in? %>
            <%= render 'like', { fish: @fish } %>
          <% end %>
          <p class="text-[13px] text-slate-500"><%= @fish.fishing_date.strftime("%Y-%m-%d %H:%M:%S") %></p>
        </div>
      </div>
    </div>
    <div class="my-3"><%= simple_format(@fish.body)%></div>
    <hr>
    <%= render 'detail', { fish: @fish } %>
    <div id="maps" class="w-full h-[calc((100vh_-_64px_-_64px)_*_0.5)] relative rounded-xl mb-10" ></div>
    <%= turbo_frame_tag "comment-list" do %>
      <%= render 'comments/comments', { fish: @fish, comments: @comments } %>
      <% if logged_in? %>
        <%= render 'comments/form', { fish: @fish, comment: @comment } %>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  // マップ
  var lat                             // 緯度
  var lng                             // 経度
  var latlng;                         // 中心の緯度, 経度
  var map;                            // 表示用のマップ
  var marker;                         // 釣果用のマーカー

  function initMap() {
      lat = <%= @fish.latitude %>
      lng = <%= @fish.longitude %>
      latlng = new google.maps.LatLng(lat, lng);
      map = new google.maps.Map(document.getElementById('maps'), {
        zoom: 8,
        center: latlng,
        mapTypeId: 'terrain',
        mapTypeControl: false,
        streetViewControl: false,
        fullscreenControl: false,
      });
      marker = new markerWithLabel.MarkerWithLabel({
          position: latlng,
          map: map,
          icon: {
            url: "<%= image_url('fish' + @fish.user.grade.to_s + '.png') %>",
            scaledSize: new google.maps.Size(30, 30)
          },
        });
  }
</script>